{{- if gt (int .Values.server.workers) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trino.worker" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: worker
spec:
  replicas: {{ .Values.server.workers }}
  selector:
    matchLabels:
      app: {{ template "trino.name" . }}
      release: {{ .Release.Name }}
      component: worker
  template:
    metadata:
      labels:
        app: {{ template "trino.name" . }}
        release: {{ .Release.Name }}
        component: worker
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: plugin-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ template "trino.worker" . }}
        - name: connectors-config-volume
          configMap:
            name: {{ template "trino.connectors" . }}
        {{ if .Values.exporters.jmx.enabled }}
        - name: config-jmx-exporter
          configMap:
            name: {{ template "trino.jmx-exporter" . }}
        {{ end }}
      initContainers:
        - name: "download-jar-trino-h3-functions-services"
          image: "mwendler/wget"
          args: [ '--no-check-certificate', 'https://github.com/The-Data-Appeal-Company/trino-h3-functions/releases/download/v363/trino-h3-functions-363-services.jar', '-P', {{ .Values.server.node.pluginDir }}/h3-functions ]
          volumeMounts:
            - mountPath: {{ .Values.server.node.pluginDir }}/h3-functions
              name: plugin-volume
        - name: "download-jar-trino-h3-functions"
          image: "mwendler/wget"
          args: [ '--no-check-certificate', 'https://github.com/The-Data-Appeal-Company/trino-h3-functions/releases/download/v363/trino-h3-functions-363.jar', '-P', {{ .Values.server.node.pluginDir }}/h3-functions]
          volumeMounts:
            - mountPath: {{ .Values.server.node.pluginDir }}/h3-functions
              name: plugin-volume
        - name: "download-jar-trino-h3"
          image: "mwendler/wget"
          args: [ '--no-check-certificate', 'https://repo1.maven.org/maven2/com/uber/h3/3.7.1/h3-3.7.1.jar', '-P', {{ .Values.server.node.pluginDir }}/h3-functions ]
          volumeMounts:
            - mountPath: {{ .Values.server.node.pluginDir }}/h3-functions
              name: plugin-volume
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.server.config.path }}
              name: config-volume
            - mountPath: {{ .Values.server.node.pluginDir }}/h3-functions
              name: plugin-volume
            - mountPath: {{ .Values.server.config.path }}/catalog
              name: connectors-config-volume
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
          readinessProbe:
            httpGet:
              path: /v1/info
              port: http
          {{ if .Values.server.gracefulShutdown.enabled }}
          lifecycle:
            preStop:
              exec:
                command: [
                    "sh", "-c",
                    "curl -v  -H \"X-Trino-User: admin\" -X PUT -d '\"SHUTTING_DOWN\"' -H \"Content-type: application/json\" http://localhost:8080/v1/info/state && sleep {{ .Values.server.gracefulShutdown.gracePeriodSeconds }}"
                ]
          {{end }}

          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}

        {{ if .Values.exporters.jmx.enabled }}
        - name: jmx-exporter
          image: "{{ .Values.exporters.jmx.image.repository }}:{{ .Values.exporters.jmx.image.tag }}"
          imagePullPolicy: {{ .Values.exporters.jmx.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.exporters.jmx.port }}
              protocol: TCP
              name: prom-exporter
          livenessProbe:
            httpGet:
              path: /metrics
              port: prom-exporter
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 60
            failureThreshold: 8
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /metrics
              port: prom-exporter
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 60
            failureThreshold: 8
            successThreshold: 1
          env:
            - name: SERVICE_PORT
              value: {{ .Values.exporters.jmx.port | quote }}
            {{- with .Values.exporters.jmx.env }}
            {{- range $key, $value := . }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          resources:
          {{ toYaml .Values.exporters.jmx.resources | indent 12 }}
          volumeMounts:
            - name: config-jmx-exporter
              mountPath: /opt/jmx_exporter/config.yml
              subPath: config.yml
      {{- end }}

      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
